// Auto-generated assembly stubs mapping NVPL *_internal_ symbols
// to the public BLAS entry points exposed by libnvpl_blas_* libraries.
// Generated once and built as a shared library that is LD_PRELOADed.

#include <dlfcn.h>

#if !defined(__aarch64__)
#error "NVPL alias shim currently implemented for AArch64 only"
#endif

#define DECLARE_ALIAS(base) \
    __asm__(".text\n" \
            ".balign 16\n" \
            ".global " #base "_internal_\n" \
            ".type " #base "_internal_, @function\n" \
            #base "_internal_:\n" \
            "b " #base "_\n");

DECLARE_ALIAS(caxpby)
DECLARE_ALIAS(caxpy)
DECLARE_ALIAS(ccopy)
DECLARE_ALIAS(cdotc)
DECLARE_ALIAS(cdotu)
DECLARE_ALIAS(cgbmv)
DECLARE_ALIAS(cgemm3m)
DECLARE_ALIAS(cgemm)
DECLARE_ALIAS(cgemmt)
DECLARE_ALIAS(cgemv)
DECLARE_ALIAS(cgerc)
DECLARE_ALIAS(cgeru)
DECLARE_ALIAS(chbmv)
DECLARE_ALIAS(chemm)
DECLARE_ALIAS(chemv)
DECLARE_ALIAS(cher2)
DECLARE_ALIAS(cher2k)
DECLARE_ALIAS(cher)
DECLARE_ALIAS(cherk)
DECLARE_ALIAS(chpmv)
DECLARE_ALIAS(chpr2)
DECLARE_ALIAS(chpr)
DECLARE_ALIAS(crotg)
DECLARE_ALIAS(cscal)
DECLARE_ALIAS(csrot)
DECLARE_ALIAS(csscal)
DECLARE_ALIAS(cswap)
DECLARE_ALIAS(csymm)
DECLARE_ALIAS(csyr2k)
DECLARE_ALIAS(csyrk)
DECLARE_ALIAS(ctbmv)
DECLARE_ALIAS(ctbsv)
DECLARE_ALIAS(ctpmv)
DECLARE_ALIAS(ctpsv)
DECLARE_ALIAS(ctrmm)
DECLARE_ALIAS(ctrmv)
DECLARE_ALIAS(ctrsm)
DECLARE_ALIAS(ctrsv)
DECLARE_ALIAS(dasum)
DECLARE_ALIAS(daxpby)
DECLARE_ALIAS(daxpy)
DECLARE_ALIAS(dcopy)
DECLARE_ALIAS(ddot)
DECLARE_ALIAS(dgbmv)
DECLARE_ALIAS(dgemm)
DECLARE_ALIAS(dgemv)
DECLARE_ALIAS(dger)
DECLARE_ALIAS(dnrm2)
DECLARE_ALIAS(drot)
DECLARE_ALIAS(drotg)
DECLARE_ALIAS(drotm)
DECLARE_ALIAS(drotmg)
DECLARE_ALIAS(dsbmv)
DECLARE_ALIAS(dscal)
DECLARE_ALIAS(dsdot)
DECLARE_ALIAS(dspmv)
DECLARE_ALIAS(dspr2)
DECLARE_ALIAS(dspr)
DECLARE_ALIAS(dswap)
DECLARE_ALIAS(dsymm)
DECLARE_ALIAS(dsymv)
DECLARE_ALIAS(dsyr2)
DECLARE_ALIAS(dsyr2k)
DECLARE_ALIAS(dsyr)
DECLARE_ALIAS(dsyrk)
DECLARE_ALIAS(dtbmv)
DECLARE_ALIAS(dtbsv)
DECLARE_ALIAS(dtpmv)
DECLARE_ALIAS(dtpsv)
DECLARE_ALIAS(dtrmm)
DECLARE_ALIAS(dtrmv)
DECLARE_ALIAS(dtrsm)
DECLARE_ALIAS(dtrsv)
DECLARE_ALIAS(dzasum)
DECLARE_ALIAS(dznrm2)
DECLARE_ALIAS(icamax)
DECLARE_ALIAS(idamax)
DECLARE_ALIAS(isamax)
DECLARE_ALIAS(izamax)
DECLARE_ALIAS(sasum)
DECLARE_ALIAS(saxpby)
DECLARE_ALIAS(saxpy)
DECLARE_ALIAS(scasum)
DECLARE_ALIAS(scnrm2)
DECLARE_ALIAS(scopy)
DECLARE_ALIAS(sdot)
DECLARE_ALIAS(sdsdot)
DECLARE_ALIAS(sgbmv)
DECLARE_ALIAS(sgemm)
DECLARE_ALIAS(sgemv)
DECLARE_ALIAS(sger)
DECLARE_ALIAS(snrm2)
DECLARE_ALIAS(srot)
DECLARE_ALIAS(srotg)
DECLARE_ALIAS(srotm)
DECLARE_ALIAS(srotmg)
DECLARE_ALIAS(ssbmv)
DECLARE_ALIAS(sscal)
DECLARE_ALIAS(sspmv)
DECLARE_ALIAS(sspr2)
DECLARE_ALIAS(sspr)
DECLARE_ALIAS(sswap)
DECLARE_ALIAS(ssymm)
DECLARE_ALIAS(ssymv)
DECLARE_ALIAS(ssyr2)
DECLARE_ALIAS(ssyr2k)
DECLARE_ALIAS(ssyr)
DECLARE_ALIAS(ssyrk)
DECLARE_ALIAS(stbmv)
DECLARE_ALIAS(stbsv)
DECLARE_ALIAS(stpmv)
DECLARE_ALIAS(stpsv)
DECLARE_ALIAS(strmm)
DECLARE_ALIAS(strmv)
DECLARE_ALIAS(strsm)
DECLARE_ALIAS(strsv)
DECLARE_ALIAS(zaxpby)
DECLARE_ALIAS(zaxpy)
DECLARE_ALIAS(zcopy)
DECLARE_ALIAS(zdotc)
DECLARE_ALIAS(zdotu)
DECLARE_ALIAS(zdrot)
DECLARE_ALIAS(zdscal)
DECLARE_ALIAS(zgbmv)
DECLARE_ALIAS(zgemm3m)
DECLARE_ALIAS(zgemm)
DECLARE_ALIAS(zgemmt)
DECLARE_ALIAS(zgemv)
DECLARE_ALIAS(zgerc)
DECLARE_ALIAS(zgeru)
DECLARE_ALIAS(zhbmv)
DECLARE_ALIAS(zhemm)
DECLARE_ALIAS(zhemv)
DECLARE_ALIAS(zher2)
DECLARE_ALIAS(zher2k)
DECLARE_ALIAS(zher)
DECLARE_ALIAS(zherk)
DECLARE_ALIAS(zhpmv)
DECLARE_ALIAS(zhpr2)
DECLARE_ALIAS(zhpr)
DECLARE_ALIAS(zrotg)
DECLARE_ALIAS(zscal)
DECLARE_ALIAS(zswap)
DECLARE_ALIAS(zsymm)
DECLARE_ALIAS(zsyr2k)
DECLARE_ALIAS(zsyrk)
DECLARE_ALIAS(ztbmv)
DECLARE_ALIAS(ztbsv)
DECLARE_ALIAS(ztpmv)
DECLARE_ALIAS(ztpsv)
DECLARE_ALIAS(ztrmm)
DECLARE_ALIAS(ztrmv)
DECLARE_ALIAS(ztrsm)
DECLARE_ALIAS(ztrsv)

void nvpl_aliases_keep(void) {}

__attribute__((constructor))
static void nvpl_aliases_ctor(void) {
    (void)dlopen("libnvpl_blas_lp64_gomp.so.0", RTLD_LAZY | RTLD_GLOBAL);
    (void)dlopen("libnvpl_lapack_lp64_gomp.so.0", RTLD_LAZY | RTLD_GLOBAL);
}
